# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: regionserver
  namespace: default
spec:
  clusterIP: None
  selector:
    app: regionserver
